import { VerbConjugation } from "../types";

export const selectedVerbList = [
  "être", // to be
  "avoir", // to have
  "faire", // to do, to make
  "dire", // to say
  "pouvoir", // to be able to (can)
  "aller", // to go
  "voir", // to see
  "vouloir", // to want
  "venir", // to come
  "devoir", // to have to (must)
  "prendre", // to take
  "trouver", // to find
  "donner", // to give
  "parler", // to speak
  "mettre", // to put
  "savoir", // to know
  "passer", // to pass, to spend (time)
  "rendre", // to return (something)
  "tenir", // to hold
  "comprendre", // to understand
];

export const tenseVerbList: VerbConjugation[] = [
  {
    infinitif: "parler",
    present: {
      Je: "parle",
      Tu: "parles",
      IlElleOn: "parle",
      Nous: "parlons",
      Vous: "parlez",
      IlsElles: "parlent",
    },
    imperfect: {
      Je: "parlais",
      Tu: "parlais",
      IlElleOn: "parlait",
      Nous: "parlions",
      Vous: "parliez",
      IlsElles: "parlaient",
    },
    perfect: {
      Je: "ai parlé",
      Tu: "as parlé",
      IlElleOn: "a parlé",
      Nous: "avons parlé",
      Vous: "avez parlé",
      IlsElles: "ont parlé",
    },
    futur: {
      Je: "parlerai",
      Tu: "parleras",
      IlElleOn: "parlera",
      Nous: "parlerons",
      Vous: "parlerez",
      IlsElles: "parleront",
    },
    subjonctifPresent: {
      Je: "parle",
      Tu: "parles",
      IlElleOn: "parle",
      Nous: "parlions",
      Vous: "parliez",
      IlsElles: "parlent",
    },
    conditionnelPresent: {
      Je: "parlerais",
      Tu: "parlerais",
      IlElleOn: "parlerait",
      Nous: "parlerions",
      Vous: "parleriez",
      IlsElles: "parleraient",
    },
    plusQuePerfect: {
      Je: "avais parlé",
      Tu: "avais parlé",
      IlElleOn: "avait parlé",
      Nous: "avions parlé",
      Vous: "aviez parlé",
      IlsElles: "avaient parlé",
    },
  },
  {
    infinitif: "être",
    present: {
      Je: "suis",
      Tu: "es",
      IlElleOn: "est",
      Nous: "sommes",
      Vous: "êtes",
      IlsElles: "sont",
    },
    imperfect: {
      Je: "étais",
      Tu: "étais",
      IlElleOn: "était",
      Nous: "étions",
      Vous: "étiez",
      IlsElles: "étaient",
    },
    perfect: {
      Je: "ai été",
      Tu: "as été",
      IlElleOn: "a été",
      Nous: "avons été",
      Vous: "avez été",
      IlsElles: "ont été",
    },
    futur: {
      Je: "serai",
      Tu: "seras",
      IlElleOn: "sera",
      Nous: "serons",
      Vous: "serez",
      IlsElles: "seront",
    },
    subjonctifPresent: {
      Je: "sois",
      Tu: "sois",
      IlElleOn: "soit",
      Nous: "soyons",
      Vous: "soyez",
      IlsElles: "soient",
    },
    conditionnelPresent: {
      Je: "serais",
      Tu: "serais",
      IlElleOn: "serait",
      Nous: "serions",
      Vous: "seriez",
      IlsElles: "seraient",
    },
    plusQuePerfect: {
      Je: "avais été",
      Tu: "avais été",
      IlElleOn: "avait été",
      Nous: "avions été",
      Vous: "aviez été",
      IlsElles: "avaient été",
    },
  },
  {
    infinitif: "avoir",
    present: {
      Je: "ai",
      Tu: "as",
      IlElleOn: "a",
      Nous: "avons",
      Vous: "avez",
      IlsElles: "ont",
    },
    imperfect: {
      Je: "avais",
      Tu: "avais",
      IlElleOn: "avait",
      Nous: "avions",
      Vous: "aviez",
      IlsElles: "avaient",
    },
    perfect: {
      Je: "ai eu",
      Tu: "as eu",
      IlElleOn: "a eu",
      Nous: "avons eu",
      Vous: "avez eu",
      IlsElles: "ont eu",
    },
    futur: {
      Je: "aurai",
      Tu: "auras",
      IlElleOn: "aura",
      Nous: "aurons",
      Vous: "aurez",
      IlsElles: "auront",
    },
    subjonctifPresent: {
      Je: "aie",
      Tu: "aies",
      IlElleOn: "ait",
      Nous: "ayons",
      Vous: "ayez",
      IlsElles: "aient",
    },
    conditionnelPresent: {
      Je: "aurais",
      Tu: "aurais",
      IlElleOn: "aurait",
      Nous: "aurions",
      Vous: "auriez",
      IlsElles: "auraient",
    },
    plusQuePerfect: {
      Je: "avais eu",
      Tu: "avais eu",
      IlElleOn: "avait eu",
      Nous: "avions eu",
      Vous: "aviez eu",
      IlsElles: "avaient eu",
    },
  },
  {
    infinitif: "faire",
    present: {
      Je: "fais",
      Tu: "fais",
      IlElleOn: "fait",
      Nous: "faisons",
      Vous: "faites",
      IlsElles: "font",
    },
    imperfect: {
      Je: "faisais",
      Tu: "faisais",
      IlElleOn: "faisait",
      Nous: "faisions",
      Vous: "faisiez",
      IlsElles: "faisaient",
    },
    perfect: {
      Je: "ai fait",
      Tu: "as fait",
      IlElleOn: "a fait",
      Nous: "avons fait",
      Vous: "avez fait",
      IlsElles: "ont fait",
    },
    futur: {
      Je: "ferai",
      Tu: "feras",
      IlElleOn: "fera",
      Nous: "ferons",
      Vous: "ferez",
      IlsElles: "feront",
    },
    subjonctifPresent: {
      Je: "fasse",
      Tu: "fasses",
      IlElleOn: "fasse",
      Nous: "fassions",
      Vous: "fassiez",
      IlsElles: "fassent",
    },
    conditionnelPresent: {
      Je: "ferais",
      Tu: "ferais",
      IlElleOn: "ferait",
      Nous: "ferions",
      Vous: "feriez",
      IlsElles: "feraient",
    },
    plusQuePerfect: {
      Je: "avais fait",
      Tu: "avais fait",
      IlElleOn: "avait fait",
      Nous: "avions fait",
      Vous: "aviez fait",
      IlsElles: "avaient fait",
    },
  },
  {
    infinitif: "dire",
    present: {
      Je: "dis",
      Tu: "dis",
      IlElleOn: "dit",
      Nous: "disons",
      Vous: "dites",
      IlsElles: "disent",
    },
    imperfect: {
      Je: "disais",
      Tu: "disais",
      IlElleOn: "disait",
      Nous: "disions",
      Vous: "disiez",
      IlsElles: "disaient",
    },
    perfect: {
      Je: "ai dit",
      Tu: "as dit",
      IlElleOn: "a dit",
      Nous: "avons dit",
      Vous: "avez dit",
      IlsElles: "ont dit",
    },
    futur: {
      Je: "dirai",
      Tu: "diras",
      IlElleOn: "dira",
      Nous: "dirons",
      Vous: "direz",
      IlsElles: "diront",
    },
    subjonctifPresent: {
      Je: "dise",
      Tu: "dises",
      IlElleOn: "dise",
      Nous: "disions",
      Vous: "disiez",
      IlsElles: "disent",
    },
    conditionnelPresent: {
      Je: "dirais",
      Tu: "dirais",
      IlElleOn: "dirait",
      Nous: "dirions",
      Vous: "diriez",
      IlsElles: "diraient",
    },
    plusQuePerfect: {
      Je: "avais dit",
      Tu: "avais dit",
      IlElleOn: "avait dit",
      Nous: "avions dit",
      Vous: "aviez dit",
      IlsElles: "avaient dit",
    },
  },
  {
    infinitif: "pouvoir",
    present: {
      Je: "peux",
      Tu: "peux",
      IlElleOn: "peut",
      Nous: "pouvons",
      Vous: "pouvez",
      IlsElles: "peuvent",
    },
    imperfect: {
      Je: "pouvais",
      Tu: "pouvais",
      IlElleOn: "pouvait",
      Nous: "pouvions",
      Vous: "pouviez",
      IlsElles: "pouvaient",
    },
    perfect: {
      Je: "ai pu",
      Tu: "as pu",
      IlElleOn: "a pu",
      Nous: "avons pu",
      Vous: "avez pu",
      IlsElles: "ont pu",
    },
    futur: {
      Je: "pourrai",
      Tu: "pourras",
      IlElleOn: "pourra",
      Nous: "pourrons",
      Vous: "pourrez",
      IlsElles: "pourront",
    },
    subjonctifPresent: {
      Je: "puisse",
      Tu: "puisses",
      IlElleOn: "puisse",
      Nous: "puissions",
      Vous: "puissiez",
      IlsElles: "puissent",
    },
    conditionnelPresent: {
      Je: "pourrais",
      Tu: "pourrais",
      IlElleOn: "pourrait",
      Nous: "pourrions",
      Vous: "pourriez",
      IlsElles: "pourraient",
    },
    plusQuePerfect: {
      Je: "avais pu",
      Tu: "avais pu",
      IlElleOn: "avait pu",
      Nous: "avions pu",
      Vous: "aviez pu",
      IlsElles: "avaient pu",
    },
  },
  {
    infinitif: "aller",
    present: {
      Je: "vais",
      Tu: "vas",
      IlElleOn: "va",
      Nous: "allons",
      Vous: "allez",
      IlsElles: "vont",
    },
    imperfect: {
      Je: "allais",
      Tu: "allais",
      IlElleOn: "allait",
      Nous: "allions",
      Vous: "alliez",
      IlsElles: "allaient",
    },
    perfect: {
      Je: "suis allé(e)",
      Tu: "es allé(e)",
      IlElleOn: "est allé(e)",
      Nous: "sommes allé(e)s",
      Vous: "êtes allé(e)s",
      IlsElles: "sont allé(e)s",
    },
    futur: {
      Je: "irai",
      Tu: "iras",
      IlElleOn: "ira",
      Nous: "irons",
      Vous: "irez",
      IlsElles: "iront",
    },
    subjonctifPresent: {
      Je: "aille",
      Tu: "ailles",
      IlElleOn: "aille",
      Nous: "allions",
      Vous: "alliez",
      IlsElles: "aillent",
    },
    conditionnelPresent: {
      Je: "irais",
      Tu: "irais",
      IlElleOn: "irait",
      Nous: "irions",
      Vous: "iriez",
      IlsElles: "iraient",
    },
    plusQuePerfect: {
      Je: "étais allé(e)",
      Tu: "étais allé(e)",
      IlElleOn: "était allé(e)",
      Nous: "étions allé(e)s",
      Vous: "étiez allé(e)s",
      IlsElles: "étaient allé(e)s",
    },
  },
  {
    infinitif: "voir",
    present: {
      Je: "vois",
      Tu: "vois",
      IlElleOn: "voit",
      Nous: "voyons",
      Vous: "voyez",
      IlsElles: "voient",
    },
    imperfect: {
      Je: "voyais",
      Tu: "voyais",
      IlElleOn: "voyait",
      Nous: "voyions",
      Vous: "voyiez",
      IlsElles: "voyaient",
    },
    perfect: {
      Je: "ai vu",
      Tu: "as vu",
      IlElleOn: "a vu",
      Nous: "avons vu",
      Vous: "avez vu",
      IlsElles: "ont vu",
    },
    futur: {
      Je: "verrai",
      Tu: "verras",
      IlElleOn: "verra",
      Nous: "verrons",
      Vous: "verrez",
      IlsElles: "verront",
    },
    subjonctifPresent: {
      Je: "voie",
      Tu: "voies",
      IlElleOn: "voie",
      Nous: "voyions",
      Vous: "voyiez",
      IlsElles: "voient",
    },
    conditionnelPresent: {
      Je: "verrais",
      Tu: "verrais",
      IlElleOn: "verrait",
      Nous: "verrions",
      Vous: "verriez",
      IlsElles: "verraient",
    },
    plusQuePerfect: {
      Je: "avais vu",
      Tu: "avais vu",
      IlElleOn: "avait vu",
      Nous: "avions vu",
      Vous: "aviez vu",
      IlsElles: "avaient vu",
    },
  },
  {
    infinitif: "vouloir",
    present: {
      Je: "veux",
      Tu: "veux",
      IlElleOn: "veut",
      Nous: "voulons",
      Vous: "voulez",
      IlsElles: "veulent",
    },
    imperfect: {
      Je: "voulais",
      Tu: "voulais",
      IlElleOn: "voulait",
      Nous: "voulions",
      Vous: "vouliez",
      IlsElles: "voulaient",
    },
    perfect: {
      Je: "ai voulu",
      Tu: "as voulu",
      IlElleOn: "a voulu",
      Nous: "avons voulu",
      Vous: "avez voulu",
      IlsElles: "ont voulu",
    },
    futur: {
      Je: "voudrai",
      Tu: "voudras",
      IlElleOn: "voudra",
      Nous: "voudrons",
      Vous: "voudrez",
      IlsElles: "voudront",
    },
    subjonctifPresent: {
      Je: "veuille",
      Tu: "veuilles",
      IlElleOn: "veuille",
      Nous: "voulions",
      Vous: "vouliez",
      IlsElles: "veuillent",
    },
    conditionnelPresent: {
      Je: "voudrais",
      Tu: "voudrais",
      IlElleOn: "voudrait",
      Nous: "voudrions",
      Vous: "voudriez",
      IlsElles: "voudraient",
    },
    plusQuePerfect: {
      Je: "avais voulu",
      Tu: "avais voulu",
      IlElleOn: "avait voulu",
      Nous: "avions voulu",
      Vous: "aviez voulu",
      IlsElles: "avaient voulu",
    },
  },
  {
    infinitif: "venir",
    present: {
      Je: "viens",
      Tu: "viens",
      IlElleOn: "vient",
      Nous: "venons",
      Vous: "venez",
      IlsElles: "viennent",
    },
    imperfect: {
      Je: "venais",
      Tu: "venais",
      IlElleOn: "venait",
      Nous: "venions",
      Vous: "veniez",
      IlsElles: "venaient",
    },
    perfect: {
      Je: "suis venu(e)",
      Tu: "es venu(e)",
      IlElleOn: "est venu(e)",
      Nous: "sommes venu(e)s",
      Vous: "êtes venu(e)s",
      IlsElles: "sont venu(e)s",
    },
    futur: {
      Je: "viendrai",
      Tu: "viendras",
      IlElleOn: "viendra",
      Nous: "viendrons",
      Vous: "viendrez",
      IlsElles: "viendront",
    },
    subjonctifPresent: {
      Je: "vienne",
      Tu: "viennes",
      IlElleOn: "vienne",
      Nous: "venions",
      Vous: "veniez",
      IlsElles: "viennent",
    },
    conditionnelPresent: {
      Je: "viendrais",
      Tu: "viendrais",
      IlElleOn: "viendrait",
      Nous: "viendrions",
      Vous: "viendriez",
      IlsElles: "viendraient",
    },
    plusQuePerfect: {
      Je: "étais venu(e)",
      Tu: "étais venu(e)",
      IlElleOn: "était venu(e)",
      Nous: "étions venu(e)s",
      Vous: "étiez venu(e)s",
      IlsElles: "étaient venu(e)s",
    },
  },
  {
    infinitif: "devoir",
    present: {
      Je: "dois",
      Tu: "dois",
      IlElleOn: "doit",
      Nous: "devons",
      Vous: "devez",
      IlsElles: "doivent",
    },
    imperfect: {
      Je: "devais",
      Tu: "devais",
      IlElleOn: "devait",
      Nous: "devions",
      Vous: "deviez",
      IlsElles: "devaient",
    },
    perfect: {
      Je: "ai dû",
      Tu: "as dû",
      IlElleOn: "a dû",
      Nous: "avons dû",
      Vous: "avez dû",
      IlsElles: "ont dû",
    },
    futur: {
      Je: "devrai",
      Tu: "devras",
      IlElleOn: "devra",
      Nous: "devrons",
      Vous: "devrez",
      IlsElles: "devront",
    },
    subjonctifPresent: {
      Je: "doive",
      Tu: "doives",
      IlElleOn: "doive",
      Nous: "devions",
      Vous: "deviez",
      IlsElles: "doivent",
    },
    conditionnelPresent: {
      Je: "devrais",
      Tu: "devrais",
      IlElleOn: "devrait",
      Nous: "devrions",
      Vous: "devriez",
      IlsElles: "devraient",
    },
    plusQuePerfect: {
      Je: "avais dû",
      Tu: "avais dû",
      IlElleOn: "avait dû",
      Nous: "avions dû",
      Vous: "aviez dû",
      IlsElles: "avaient dû",
    },
  },
  {
    infinitif: "prendre",
    present: {
      Je: "prends",
      Tu: "prends",
      IlElleOn: "prend",
      Nous: "prenons",
      Vous: "prenez",
      IlsElles: "prennent",
    },
    imperfect: {
      Je: "prenais",
      Tu: "prenais",
      IlElleOn: "prenait",
      Nous: "prenions",
      Vous: "preniez",
      IlsElles: "prenaient",
    },
    perfect: {
      Je: "ai pris",
      Tu: "as pris",
      IlElleOn: "a pris",
      Nous: "avons pris",
      Vous: "avez pris",
      IlsElles: "ont pris",
    },
    futur: {
      Je: "prendrai",
      Tu: "prendras",
      IlElleOn: "prendra",
      Nous: "prendrons",
      Vous: "prendrez",
      IlsElles: "prendront",
    },
    subjonctifPresent: {
      Je: "prenne",
      Tu: "prennes",
      IlElleOn: "prenne",
      Nous: "prenions",
      Vous: "preniez",
      IlsElles: "prennent",
    },
    conditionnelPresent: {
      Je: "prendrais",
      Tu: "prendrais",
      IlElleOn: "prendrait",
      Nous: "prendrions",
      Vous: "prendriez",
      IlsElles: "prendraient",
    },
    plusQuePerfect: {
      Je: "avais pris",
      Tu: "avais pris",
      IlElleOn: "avait pris",
      Nous: "avions pris",
      Vous: "aviez pris",
      IlsElles: "avaient pris",
    },
  },
  {
    infinitif: "trouver",
    present: {
      Je: "trouve",
      Tu: "trouves",
      IlElleOn: "trouve",
      Nous: "trouvons",
      Vous: "trouvez",
      IlsElles: "trouvent",
    },
    imperfect: {
      Je: "trouvais",
      Tu: "trouvais",
      IlElleOn: "trouvait",
      Nous: "trouvions",
      Vous: "trouviez",
      IlsElles: "trouvaient",
    },
    perfect: {
      Je: "ai trouvé",
      Tu: "as trouvé",
      IlElleOn: "a trouvé",
      Nous: "avons trouvé",
      Vous: "avez trouvé",
      IlsElles: "ont trouvé",
    },
    futur: {
      Je: "trouverai",
      Tu: "trouveras",
      IlElleOn: "trouvera",
      Nous: "trouverons",
      Vous: "trouverez",
      IlsElles: "trouveront",
    },
    subjonctifPresent: {
      Je: "trouve",
      Tu: "trouves",
      IlElleOn: "trouve",
      Nous: "trouvions",
      Vous: "trouviez",
      IlsElles: "trouvent",
    },
    conditionnelPresent: {
      Je: "trouverais",
      Tu: "trouverais",
      IlElleOn: "trouverait",
      Nous: "trouverions",
      Vous: "trouveriez",
      IlsElles: "trouveraient",
    },
    plusQuePerfect: {
      Je: "avais trouvé",
      Tu: "avais trouvé",
      IlElleOn: "avait trouvé",
      Nous: "avions trouvé",
      Vous: "aviez trouvé",
      IlsElles: "avaient trouvé",
    },
  },
  {
    infinitif: "donner",
    present: {
      Je: "donne",
      Tu: "donnes",
      IlElleOn: "donne",
      Nous: "donnons",
      Vous: "donnez",
      IlsElles: "donnent",
    },
    imperfect: {
      Je: "donnais",
      Tu: "donnais",
      IlElleOn: "donnait",
      Nous: "donnions",
      Vous: "donniez",
      IlsElles: "donnaient",
    },
    perfect: {
      Je: "ai donné",
      Tu: "as donné",
      IlElleOn: "a donné",
      Nous: "avons donné",
      Vous: "avez donné",
      IlsElles: "ont donné",
    },
    futur: {
      Je: "donnerai",
      Tu: "donneras",
      IlElleOn: "donnera",
      Nous: "donnerons",
      Vous: "donnerez",
      IlsElles: "donneront",
    },
    subjonctifPresent: {
      Je: "donne",
      Tu: "donnes",
      IlElleOn: "donne",
      Nous: "donnions",
      Vous: "donniez",
      IlsElles: "donnent",
    },
    conditionnelPresent: {
      Je: "donnerais",
      Tu: "donnerais",
      IlElleOn: "donnerait",
      Nous: "donnerions",
      Vous: "donneriez",
      IlsElles: "donneraient",
    },
    plusQuePerfect: {
      Je: "avais donné",
      Tu: "avais donné",
      IlElleOn: "avait donné",
      Nous: "avions donné",
      Vous: "aviez donné",
      IlsElles: "avaient donné",
    },
  },
  {
    infinitif: "mettre",
    present: {
      Je: "mets",
      Tu: "mets",
      IlElleOn: "met",
      Nous: "mettons",
      Vous: "mettez",
      IlsElles: "mettent",
    },
    imperfect: {
      Je: "mettais",
      Tu: "mettais",
      IlElleOn: "mettait",
      Nous: "mettions",
      Vous: "mettiez",
      IlsElles: "mettaient",
    },
    perfect: {
      Je: "ai mis",
      Tu: "as mis",
      IlElleOn: "a mis",
      Nous: "avons mis",
      Vous: "avez mis",
      IlsElles: "ont mis",
    },
    futur: {
      Je: "mettrai",
      Tu: "mettras",
      IlElleOn: "mettra",
      Nous: "mettrons",
      Vous: "mettrez",
      IlsElles: "mettront",
    },
    subjonctifPresent: {
      Je: "mette",
      Tu: "mettes",
      IlElleOn: "mette",
      Nous: "mettions",
      Vous: "mettiez",
      IlsElles: "mettent",
    },
    conditionnelPresent: {
      Je: "mettrais",
      Tu: "mettrais",
      IlElleOn: "mettrait",
      Nous: "mettrions",
      Vous: "mettriez",
      IlsElles: "mettraient",
    },
    plusQuePerfect: {
      Je: "avais mis",
      Tu: "avais mis",
      IlElleOn: "avait mis",
      Nous: "avions mis",
      Vous: "aviez mis",
      IlsElles: "avaient mis",
    },
  },
  {
    infinitif: "savoir",
    present: {
      Je: "sais",
      Tu: "sais",
      IlElleOn: "sait",
      Nous: "savons",
      Vous: "savez",
      IlsElles: "savent",
    },
    imperfect: {
      Je: "savais",
      Tu: "savais",
      IlElleOn: "savait",
      Nous: "savions",
      Vous: "saviez",
      IlsElles: "savaient",
    },
    perfect: {
      Je: "ai su",
      Tu: "as su",
      IlElleOn: "a su",
      Nous: "avons su",
      Vous: "avez su",
      IlsElles: "ont su",
    },
    futur: {
      Je: "saurai",
      Tu: "sauras",
      IlElleOn: "saura",
      Nous: "saurons",
      Vous: "saurez",
      IlsElles: "sauront",
    },
    subjonctifPresent: {
      Je: "sache",
      Tu: "saches",
      IlElleOn: "sache",
      Nous: "sachions",
      Vous: "sachiez",
      IlsElles: "sachent",
    },
    conditionnelPresent: {
      Je: "saurais",
      Tu: "saurais",
      IlElleOn: "saurait",
      Nous: "saurions",
      Vous: "sauriez",
      IlsElles: "s sauraient",
    },
    plusQuePerfect: {
      Je: "avais su",
      Tu: "avais su",
      IlElleOn: "avait su",
      Nous: "avions su",
      Vous: "aviez su",
      IlsElles: "avaient su",
    },
  },
  {
    infinitif: "passer",
    present: {
      Je: "passe",
      Tu: "passes",
      IlElleOn: "passe",
      Nous: "passons",
      Vous: "passez",
      IlsElles: "passent",
    },
    imperfect: {
      Je: "passais",
      Tu: "passais",
      IlElleOn: "passait",
      Nous: "passions",
      Vous: "passiez",
      IlsElles: "passaient",
    },
    perfect: {
      Je: "ai passé",
      Tu: "as passé",
      IlElleOn: "a passé",
      Nous: "avons passé",
      Vous: "avez passé",
      IlsElles: "ont passé",
    },
    futur: {
      Je: "passerai",
      Tu: "passeras",
      IlElleOn: "passera",
      Nous: "passerons",
      Vous: "passerez",
      IlsElles: "passeront",
    },
    subjonctifPresent: {
      Je: "passe",
      Tu: "passes",
      IlElleOn: "passe",
      Nous: "passions",
      Vous: "passiez",
      IlsElles: "passent",
    },
    conditionnelPresent: {
      Je: "passerais",
      Tu: "passerais",
      IlElleOn: "passerait",
      Nous: "passerions",
      Vous: "passeriez",
      IlsElles: "passeraient",
    },
    plusQuePerfect: {
      Je: "avais passé",
      Tu: "avais passé",
      IlElleOn: "avait passé",
      Nous: "avions passé",
      Vous: "aviez passé",
      IlsElles: "avaient passé",
    },
  },
  {
    infinitif: "rendre",
    present: {
      Je: "rends",
      Tu: "rends",
      IlElleOn: "rend",
      Nous: "rendons",
      Vous: "rendez",
      IlsElles: "rendent",
    },
    imperfect: {
      Je: "rendais",
      Tu: "rendais",
      IlElleOn: "rendait",
      Nous: "rendions",
      Vous: "rendiez",
      IlsElles: "rendaient",
    },
    perfect: {
      Je: "ai rendu",
      Tu: "as rendu",
      IlElleOn: "a rendu",
      Nous: "avons rendu",
      Vous: "avez rendu",
      IlsElles: "ont rendu",
    },
    futur: {
      Je: "rendrai",
      Tu: "rendras",
      IlElleOn: "rendra",
      Nous: "rendrons",
      Vous: "rendrez",
      IlsElles: "rendront",
    },
    subjonctifPresent: {
      Je: "rende",
      Tu: "rendes",
      IlElleOn: "rende",
      Nous: "rendions",
      Vous: "rendiez",
      IlsElles: "rendent",
    },
    conditionnelPresent: {
      Je: "rendrais",
      Tu: "rendrais",
      IlElleOn: "rendrait",
      Nous: "rendrions",
      Vous: "rendriez",
      IlsElles: "rendraient",
    },
    plusQuePerfect: {
      Je: "avais rendu",
      Tu: "avais rendu",
      IlElleOn: "avait rendu",
      Nous: "avions rendu",
      Vous: "aviez rendu",
      IlsElles: "avaient rendu",
    },
  },
  {
    infinitif: "tenir",
    present: {
      Je: "tiens",
      Tu: "tiens",
      IlElleOn: "tient",
      Nous: "tenons",
      Vous: "tenez",
      IlsElles: "tiennent",
    },
    imperfect: {
      Je: "tenais",
      Tu: "tenais",
      IlElleOn: "tenait",
      Nous: "tenions",
      Vous: "teniez",
      IlsElles: "tenaient",
    },
    perfect: {
      Je: "ai tenu",
      Tu: "as tenu",
      IlElleOn: "a tenu",
      Nous: "avons tenu",
      Vous: "avez tenu",
      IlsElles: "ont tenu",
    },
    futur: {
      Je: "tiendrai",
      Tu: "tiendras",
      IlElleOn: "tiendra",
      Nous: "tiendrons",
      Vous: "tiendrez",
      IlsElles: "tiendront",
    },
    subjonctifPresent: {
      Je: "tienne",
      Tu: "tiennes",
      IlElleOn: "tienne",
      Nous: "tenions",
      Vous: "teniez",
      IlsElles: "tiennent",
    },
    conditionnelPresent: {
      Je: "tiendrais",
      Tu: "tiendrais",
      IlElleOn: "tiendrait",
      Nous: "tiendrions",
      Vous: "tiendriez",
      IlsElles: "tiendraient",
    },
    plusQuePerfect: {
      Je: "avais tenu",
      Tu: "avais tenu",
      IlElleOn: "avait tenu",
      Nous: "avions tenu",
      Vous: "aviez tenu",
      IlsElles: "avaient tenu",
    },
  },
  {
    infinitif: "comprendre",
    present: {
      Je: "comprends",
      Tu: "comprends",
      IlElleOn: "comprend",
      Nous: "comprenons",
      Vous: "comprenez",
      IlsElles: "comprennent",
    },
    imperfect: {
      Je: "comprenais",
      Tu: "comprenais",
      IlElleOn: "comprenait",
      Nous: "comprenaions",
      Vous: "comprenez",
      IlsElles: "comprenait",
    },
    perfect: {
      Je: "ai compris",
      Tu: "as compris",
      IlElleOn: "a compris",
      Nous: "avons compris",
      Vous: "avez compris",
      IlsElles: "ont compris",
    },
    futur: {
      Je: "comprendrai",
      Tu: "comprendras",
      IlElleOn: "comprendra",
      Nous: "comprendrons",
      Vous: "comprenez",
      IlsElles: "comprendront",
    },
    subjonctifPresent: {
      Je: "comprenne",
      Tu: "comprennes",
      IlElleOn: "comprenne",
      Nous: "comprennions",
      Vous: "comprenniez",
      IlsElles: "comprennent",
    },
    conditionnelPresent: {
      Je: "comprendrais",
      Tu: "comprendrais",
      IlElleOn: "comprendrait",
      Nous: "comprendrions",
      Vous: "comprendriez",
      IlsElles: "comprendraient",
    },
    plusQuePerfect: {
      Je: "avais compris",
      Tu: "avais compris",
      IlElleOn: "avait compris",
      Nous: "avions compris",
      Vous: "aviez compris",
      IlsElles: "avaient compris",
    },
  },
];
